# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker-compose up -d demoapp
  displayName: 'Run Demo App'

- script: docker-compose up -d hub firefox chrome
  displayName: 'Run Robot & Selenium Hub'

- script: docker-compose run test-gc
  displayName: 'Run Test'


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: |
      **/results/**/outputxunit.xml
    mergeTestResults: true
    failTaskOnFailedTests: true